version: "3.8"

services:
  api:
    container_name: chat-app-api
    restart: unless-stopped
    image: chat-app-api-prod:1.0.0
    build:
      context: api
      target: production
      dockerfile: DockerFile
    ports:
      - 9000:9000
    networks:
      - shared-network
  
  client:
    container_name: chat-app-client
    restart: unless-stopped
    image: chat-app-client-prod:1.0.0
    build:
      context:  client
      target: production
      dockerfile: DockerFile
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:

    