FROM node:16.16.0 AS Production

ENV MONGODB_URL=mongodb+srv://admin:Sanket230597@cluster0.kcvew5q.mongodb.net/?retryWrites=true&w=majority
ENV PUSHER_APPID=1444121
ENV PUSHER_KEY=03dd74eaefa15e1b25a8
ENV PUSHER_SECRET=0ba620fd0fa77562580e
ENV PUSHER_CLUSTER=ap2
ENV PUSHER_USETLS=true

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .
 
RUN yarn run build-ts

EXPOSE 9000

CMD [ "yarn","run", "start"]